### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by d-Pixie** [ire4ever1190/mike#1]
From semver.org (assuming that we are being rational about versioning here 😄 ):

*4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.*

So there is no need to change major version to signify breakage in 0.x versions. In fact:

*5. Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.*

By setting a version 1.x you basically signal that the public API of the package IS stable, quite the reverse of what you intended.

I would suggest (though that is also in conflict with semver rules) that you re-release the current version as a 0.x release to show that it is still in flux.

**Comment by ire4ever1190** [comment]
Thanks for bringing this to my attention!
I think the issue is to do with my wording in the readme?
> The 1.x does not mean it is stable, it just means it is incompatible with previous versions

I do plan to keep the current api the same for future releases and don't plan on changing it. When I wrote it I more meant that I don't consider it production ready. Would fixing that sentence in the readme resolve the issue?
