### ISSUE TITLE
Issue while posting.

### ISSUE THREAD

**Issue by AritraBanik08** [ire4ever1190/mike#29]
Whenever I am trying to post and redirect it is not working can you tell me why? Thank you great work love it but having sum issues so thank you for the help.

**Comment by ire4ever1190** [comment]
Can you give an example? This works with curl
```nim
import mike

"/test" -> post:
  ctx.redirect("/hello")

"/hello" -> post:
  ctx.send("Hello world")

run()
```

**Comment by AritraBanik08** [comment]
I did that can you please check the code [here](https://gitlab.com/a60030/ab). If you want you can fork it and fix it. Thank you for your help.

**Comment by ire4ever1190** [comment]
Think the issue is [here](https://gitlab.com/a60030/ab/-/blob/main/src/n8.nim?ref_type=heads#L113) since the route doesn't support handling POST requests (You can do `"/reservation-summary" -> [get, post]` to handle both).

`Location` preserves the method when redirecting so it will redirect as a POST request, not a GET (See second paragraph [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location)).

**Comment by AritraBanik08** [comment]
Thanks for the great help. Love the framework and keep up the good work.
